# Generated by Django 4.2.6 on 2023-10-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=400, null=True)),
                ('body', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(null=True, upload_to='black_blog/')),
                ('view_count', models.BigIntegerField(default=0)),
            ],
        ),
    ]
