# Generated by Django 4.2.6 on 2023-11-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=350)),
                ('icon', models.ImageField(upload_to='icon/')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
