# Generated by Django 4.2.6 on 2023-12-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_blog', '0003_sitetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
